### ISSUE TITLE
Very strong security breach

### ISSUE THREAD

**Issue by mahavakya** [Morozov-5F/datad-app#2]
<pre>
Hey man,
We are anonymous...

Just FIY

You have a very strong security breach.

- <a href="https://github.com/aristovz/repo/blob/d035b972de0179c1e634f4c354ab2c2ec83847f7/parser.php#L4-L5">https://github.com/aristovz/repo/blob/d035b972de0179c1e634f4c354ab2c2ec83847f7/parser.php#L4-L5</a>
- <a href="https://github.com/Morozov-5F/datad-app/blob/311ba13412bfebee3398e6ee5fbb535e4948d109/backend/parser.php#L4-L5">https://github.com/Morozov-5F/datad-app/blob/311ba13412bfebee3398e6ee5fbb535e4948d109/backend/parser.php#L4-L5</a>
- <a href="https://github.com/search?q=morozov5F&type=Code&utf8=Code&utf8=✓">https://github.com/search?q=morozov5F&type=Code&utf8=Code&utf8=✓</a>

We dont steal any of your private data. We just log-in and log out to check if the password correct.

We strongly recommend to 
- immediately change this password on all resources where you used it
- use long password-length  (at least 15 alphanumeric, but we recommend 20)
- <a href="https://twofactorauth.org/">turn on 2FA everywhere you can</a>
- don't enter your password in source code
- check your accounts <a href="https://haveibeenpwned.com/">here</a> and <a href="https://haveibeenpwned.com/Passwords">there</a>
- read this <a href="https://spreadprivacy.com/privacy-tips/home">security recommendations</a>

We're small team of anonymous hackers and we are trying to make internet open and highly secure. 
We never use any breaches to our own purposes.

Have a nice day!

00098e00  85 5a ee 32 a0 53 4f e9  ca 9a 96 05 68 2b 1b 12  |.Z.2.SO.....h+..|
00098e10  5d 2a 02 26 88 38 82 d1  20 e9 a8 50 bd 99 d1 66  |]*.&.8.. ..P...f|
00098e20  28 64 f6 82 26 1e f7 91  07 16 96 7c 30 dd ea 33  |(d..&......|0..3|
00098e30  f6 a9 40 e9 88 0f 7d 72  24 41 13 70 98 35 2f 8e  |..@...}r$A.p.5/.|
00098e40  d0 2a 4e eb a8 9f f0 81  6c 03 76 9f a1 99 6d b0  |.*N.....l.v...m.|
00098e50  96 97 63 f1 3e 8e f1 d9  69 f7 46 f3 2e 8b 31 fc  |..c.>...i.F...1.|
00098e60  41 8f be 0e 0b 8b ca c0  2c f4 e1 b1 f8 84 4c 03  |A.......,.....L.|
00098e70  11 9a 88 43 a1 b2 5b 09  7b e2 b4 35 a2 2c 28 9d  |...C..[.{..5.,(.|
00098e80  7d be 9c f5 6d 94 a2 c6  5d df 5a f8 8d 77 7e 15  |}...m...].Z..w~.|
00098e90  5f df 69 36 16 1e ee a6  d3 31 ba 5a 67 5c 0e d7  |_.i6.....1.Zg\..|
00098ea0  02 33 65 08 95 33 ca a3  6b 0b ca 25 92 93 0b 4a  |.3e..3..k..%...J|
00098eb0  79 55 39 7a c1 d3 40 85  9e 53 9c ba 7b 27 96 51  |yU9z..@..S..{'.Q|
</pre>

**Comment by Morozov-5F** [comment]
@mahavakya, thanks
